services:
  oskari-db:
    image: postgis/postgis
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=oskari
      - POSTGRES_PASSWORD=oskari
      - POSTGRES_DB=oskaridb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oskari -d oskaridb"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  oskari-redis:
    image: redis

  oskari:
    build: .
    ports:
      - 8080:8080
    depends_on:
      oskari-db:
        condition: service_healthy
        restart: true
